baseURL = "/"
languageCode = "en-us"
title = "Moritz Lampkemeyer"
theme = "marked"
copyright = "2018 Moritz Lampkemeyer"
PygmentsStyle = "github"

[params]
  author = "Moritz Lampkemeyer"
  description = "The personal website of Moritz Lampkemeyer"

[[menu.main]]
  name = "About"
  url = "/about/"
 [[menu.main]]
  name = "Privacy"
  url = "/privacy/"
[[menu.main]]
  name = "Imprint"
  url = "/imprint/"
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
